name: Sandbox
on:
  push:
    branches: [ master ]
jobs:
  without-cmake:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    env:
      LLVM_VERSION: 16.0
      LLVM_PATH: ${{ github.workspace }}/llvm
    steps:
      - uses: actions/checkout@v3
      - name: Cache LLVM
        uses: actions/cache@v3
        id: cache-llvm
        with:
          path: ${{ env.LLVM_PATH }}
          key: ${{ runner.os }}-llvm-${{ env.LLVM_VERSION }}
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - run: clang++ main.cpp --std=c++20 --output=main.exe -fexperimental-library -stdlib=libc++
      - run: ./main.exe
